version: "3.6"

services:
  frontend:
    container_name: ${PROJECT_NAME}
    image: openizr/node:2.0.1-dev
    env_file:
      - .env
    ports:
      - "${HOST_IP}:${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: sh -c "yarn && yarn run dev"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
